<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TuckClip.Platform.Windows</RootNamespace>
    <AssemblyName>TuckClip.Platform.Windows</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TuckClip.Core/TuckClip.Core.csproj" />
  </ItemGroup>
</Project>
