import AppKit
import Foundation
import XCTest
@testable import TuckClip

/// Contract tests for TuckClip's portable pasteboard protocol.
///
/// Every test uses a process-unique named pasteboard and UserDefaults suite, so
/// command-line hosted XCTest never reads or overwrites the user's clipboard or
/// preferences.
@MainActor
final class PasteboardServicesTests: XCTestCase {
    private let timestamp = Date(timeIntervalSince1970: 1_800_000_000)

    func testReaderNormalizesExternalTextLinkImageAndFiles() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )

        try requireReadableHostedPasteboard(reader)

        let textItem = NSPasteboardItem()
        XCTAssertTrue(textItem.setString("中文剪贴板 🪺", forType: .string))
        try fixture.replaceContents(with: [textItem])
        let textCapture = try requireCapture(from: reader)
        XCTAssertEqual(textCapture.kind, .text)
        XCTAssertEqual(textCapture.plainText, "中文剪贴板 🪺")
        XCTAssertFalse(textCapture.fingerprint.isEmpty)

        let link = "https://example.com/tuckclip?q=reader"
        let linkItem = NSPasteboardItem()
        XCTAssertTrue(linkItem.setString(link, forType: .string))
        XCTAssertTrue(linkItem.setString(link, forType: .URL))
        try fixture.replaceContents(with: [linkItem])
        let linkCapture = try requireCapture(from: reader)
        XCTAssertEqual(linkCapture.kind, .link)
        XCTAssertEqual(linkCapture.plainText, link)

        let imageItem = NSPasteboardItem()
        XCTAssertTrue(imageItem.setData(Self.pngData, forType: .png))
        try fixture.replaceContents(with: [imageItem])
        let imageCapture = try requireCapture(from: reader)
        XCTAssertEqual(imageCapture.kind, .image)
        XCTAssertEqual(imageCapture.imageData, Self.pngData)

        let filePaths = ["/tmp/TuckClip 测试.txt", "/tmp/second.pdf"]
        let fileItems = filePaths.map { path in
            let item = NSPasteboardItem()
            XCTAssertTrue(
                item.setString(
                    URL(fileURLWithPath: path).absoluteString,
                    forType: .fileURL
                )
            )
            return item
        }
        try fixture.replaceContents(with: fileItems)
        let filesCapture = try requireCapture(from: reader)
        XCTAssertEqual(filesCapture.kind, .files)
        XCTAssertEqual(filesCapture.filePaths, filePaths)
    }

    func testReaderFiltersConcealedTransientAndInternalMarkerItems() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )

        try requireReadableHostedPasteboard(reader)

        for ignoredTypeName in [
            "org.nspasteboard.concealedtype",
            "org.nspasteboard.transienttype",
            "org.nspasteboard.autogeneratedtype"
        ] {
            let item = NSPasteboardItem()
            XCTAssertTrue(item.setString("不得记录", forType: .string))
            XCTAssertTrue(
                item.setString(
                    "1",
                    forType: NSPasteboard.PasteboardType(ignoredTypeName)
                )
            )
            try fixture.replaceContents(with: [item])
            XCTAssertNil(
                reader.readCapture(timestamp: timestamp, sourceApplication: nil),
                "Expected \(ignoredTypeName) to be filtered"
            )
        }

        let internalItem = NSPasteboardItem()
        XCTAssertTrue(internalItem.setString("不得回录", forType: .string))
        XCTAssertTrue(
            internalItem.setString(
                UUID().uuidString,
                forType: PasteboardReader.internalMarkerType
            )
        )
        try fixture.replaceContents(with: [internalItem])
        XCTAssertNil(reader.readCapture(timestamp: timestamp, sourceApplication: nil))
    }

    func testReaderFiltersHighConfidencePrivateKeyBoundariesWithoutBroadTextBlocking() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )

        try requireReadableHostedPasteboard(reader)

        for privateKeyBoundary in [
            "-----BEGIN PRIVATE KEY-----",
            "-----BEGIN ENCRYPTED PRIVATE KEY-----",
            "-----BEGIN RSA PRIVATE KEY-----",
            "-----BEGIN EC PRIVATE KEY-----",
            "-----BEGIN DSA PRIVATE KEY-----",
            "-----BEGIN OPENSSH PRIVATE KEY-----",
            "-----BEGIN PGP PRIVATE KEY BLOCK-----",
            "-----BEGIN PGP SECRET KEY BLOCK-----"
        ] {
            let item = NSPasteboardItem()
            XCTAssertTrue(item.setString(
                "\(privateKeyBoundary)\nprivate-material\n-----END PRIVATE KEY-----",
                forType: .string
            ))
            try fixture.replaceContents(with: [item])
            XCTAssertNil(
                reader.readCapture(timestamp: timestamp, sourceApplication: nil),
                "Expected \(privateKeyBoundary) to be filtered"
            )
        }

        for safeText in [
            "-----BEGIN PUBLIC KEY-----\npublic-material\n-----END PUBLIC KEY-----",
            "文档提到了 BEGIN PRIVATE KEY，但这里没有标准边界行。"
        ] {
            let item = NSPasteboardItem()
            XCTAssertTrue(item.setString(safeText, forType: .string))
            try fixture.replaceContents(with: [item])
            XCTAssertEqual(try requireCapture(from: reader).plainText, safeText)
        }
    }

    func testReaderRejectsTextAboveMetadataSafetyLimit() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )
        try requireReadableHostedPasteboard(reader)

        let item = NSPasteboardItem()
        XCTAssertTrue(item.setString(
            String(repeating: "x", count: AppSettings.maximumTextCaptureSizeBytes + 1),
            forType: .string
        ))
        try fixture.replaceContents(with: [item])

        XCTAssertNil(reader.readCapture(timestamp: timestamp, sourceApplication: nil))
    }

    func testMonitorAttributesPendingCopyToApplicationBeforeActivationSwitch() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }

        guard let excludedApplication = NSWorkspace.shared.runningApplications.first(where: {
            guard let bundleIdentifier = $0.bundleIdentifier else { return false }
            return bundleIdentifier != Bundle.main.bundleIdentifier
        }), let excludedBundleIdentifier = excludedApplication.bundleIdentifier else {
            throw XCTSkip("No external running application is available for source attribution.")
        }

        fixture.settings.excludedBundleIdentifiers = [excludedBundleIdentifier]
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )
        try requireReadableHostedPasteboard(reader)

        let monitor = ClipboardMonitor(settings: fixture.settings, reader: reader)
        var captures: [ClipboardCapture] = []
        monitor.onCapture = { captures.append($0) }
        monitor.start()
        defer { monitor.stop() }

        // Cache an excluded source, then simulate the activation notification
        // arriving after that app changed the pasteboard. The pending value must
        // be consumed against the old source before the cache is replaced.
        monitor.handleActivatedApplication(excludedApplication)
        let secretItem = NSPasteboardItem()
        XCTAssertTrue(secretItem.setString("password-manager secret", forType: .string))
        try fixture.replaceContents(with: [secretItem])
        monitor.handleActivatedApplication(nil)

        XCTAssertTrue(captures.isEmpty)
        XCTAssertNil(monitor.lastCapture)

        // The excluded change count was still advanced. A later copy from the new
        // (unknown here for deterministic testing) source is captured exactly once.
        let ordinaryItem = NSPasteboardItem()
        XCTAssertTrue(ordinaryItem.setString("ordinary clipboard value", forType: .string))
        try fixture.replaceContents(with: [ordinaryItem])
        monitor.pollNow()
        monitor.pollNow()

        XCTAssertEqual(captures.count, 1)
        XCTAssertEqual(captures.first?.plainText, "ordinary clipboard value")
        XCTAssertNil(captures.first?.sourceBundleIdentifier)
    }

    func testWriterRestoresTextAndLinkWithInternalMarker() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let writer = PasteboardWriter(pasteboard: fixture.pasteboard)

        let text = "保留 Unicode 文本 🪺"
        let textReceipt = try writer.write(kind: .text, plainText: text)
        XCTAssertEqual(textReceipt.changeCount, fixture.pasteboard.changeCount)
        let textItem = try XCTUnwrap(fixture.pasteboard.pasteboardItems?.first)
        XCTAssertEqual(textItem.string(forType: .string), text)
        XCTAssertNil(textItem.string(forType: .URL))
        assertInternalMarker(on: textItem)

        let link = "https://example.com/restored"
        let linkReceipt = try writer.write(kind: .link, plainText: link)
        XCTAssertEqual(linkReceipt.changeCount, fixture.pasteboard.changeCount)
        let linkItem = try XCTUnwrap(fixture.pasteboard.pasteboardItems?.first)
        XCTAssertEqual(linkItem.string(forType: .string), link)
        XCTAssertEqual(linkItem.string(forType: .URL), link)
        assertInternalMarker(on: linkItem)
    }

    func testWriterRestoresImageAndFileListWithInternalMarker() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let writer = PasteboardWriter(pasteboard: fixture.pasteboard)

        _ = try writer.write(kind: .image, imageData: Self.pngData)
        let imageItem = try XCTUnwrap(fixture.pasteboard.pasteboardItems?.first)
        XCTAssertEqual(imageItem.data(forType: .png), Self.pngData)
        assertInternalMarker(on: imageItem)

        let filePaths = ["/tmp/TuckClip A.txt", "/tmp/报告.pdf"]
        _ = try writer.write(kind: .files, filePaths: filePaths)
        let fileItems = try XCTUnwrap(fixture.pasteboard.pasteboardItems)
        XCTAssertEqual(fileItems.count, 2)
        let restoredPaths = try fileItems.map { item in
            let value = try XCTUnwrap(item.string(forType: .fileURL))
            return try XCTUnwrap(URL(string: value)).standardizedFileURL.path
        }
        XCTAssertEqual(restoredPaths, filePaths)
        assertInternalMarker(on: fileItems[0])
    }

    func testReaderRejectsOutputWrittenByWriter() throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let reader = PasteboardReader(
            pasteboard: fixture.pasteboard,
            settings: fixture.settings
        )
        let writer = PasteboardWriter(pasteboard: fixture.pasteboard)

        try requireReadableHostedPasteboard(reader)
        _ = try writer.write(kind: .text, plainText: "TuckClip 自己恢复的内容")

        XCTAssertNil(reader.readCapture(timestamp: timestamp, sourceApplication: nil))
    }

    private func requireCapture(
        from reader: PasteboardReader,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws -> ClipboardCapture {
        if let capture = reader.readCapture(
            timestamp: timestamp,
            sourceApplication: nil
        ) {
            return capture
        }

        XCTFail("Expected the named pasteboard value to be captured", file: file, line: line)
        throw TestFailure.captureUnexpectedlyMissing
    }

    private func requireReadableHostedPasteboard(_ reader: PasteboardReader) throws {
        guard reader.accessStatus.allowsBackgroundCapture else {
            throw XCTSkip(
                "This macOS test host denies programmatic pasteboard reads. Writer and marker assertions remain deterministic."
            )
        }
    }

    private func assertInternalMarker(
        on item: NSPasteboardItem,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        let marker = item.string(forType: PasteboardReader.internalMarkerType)
        XCTAssertNotNil(marker, file: file, line: line)
        XCTAssertNotNil(marker.flatMap(UUID.init(uuidString:)), file: file, line: line)
    }

    private enum TestFailure: Error {
        case captureUnexpectedlyMissing
    }

    private static let pngData = Data(base64Encoded:
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    )!
}

@MainActor
private final class Fixture {
    let pasteboard: NSPasteboard
    let settings: AppSettings

    private let defaults: UserDefaults
    private let defaultsSuiteName: String

    init() throws {
        let identifier = UUID().uuidString
        defaultsSuiteName = "TuckClipTests.PasteboardServices.\(identifier)"
        guard let defaults = UserDefaults(suiteName: defaultsSuiteName) else {
            throw FixtureError.unableToCreateDefaultsSuite
        }
        self.defaults = defaults
        defaults.removePersistentDomain(forName: defaultsSuiteName)

        settings = AppSettings(defaults: defaults)
        settings.excludedBundleIdentifiers = []
        settings.capturesImages = true

        pasteboard = NSPasteboard(
            name: NSPasteboard.Name("io.github.iajihga.TuckClipTests.\(identifier)")
        )
        pasteboard.clearContents()
    }

    func replaceContents(with items: [NSPasteboardItem]) throws {
        pasteboard.clearContents()
        guard pasteboard.writeObjects(items) else {
            throw FixtureError.pasteboardRejectedWrite
        }
    }

    func cleanUp() {
        pasteboard.clearContents()
        pasteboard.releaseGlobally()
        defaults.removePersistentDomain(forName: defaultsSuiteName)
    }

    private enum FixtureError: Error {
        case pasteboardRejectedWrite
        case unableToCreateDefaultsSuite
    }
}
