import AppKit
import CryptoKit
import Foundation

/// The General pasteboard access policy reported by macOS 15.4 and later.
enum PasteboardAccessStatus: Equatable, Sendable {
    /// Older macOS releases do not expose a pasteboard access policy.
    case unavailable
    /// The app has not triggered the system's first pasteboard access prompt.
    case notDetermined
    case ask
    case alwaysAllow
    case alwaysDeny

    var allowsBackgroundCapture: Bool {
        switch self {
        case .unavailable, .notDetermined, .ask, .alwaysAllow:
            return true
        case .alwaysDeny:
            return false
        }
    }

    var needsAlwaysAllowEducation: Bool {
        self == .notDetermined || self == .ask
    }
}

/// Reads and normalizes the portable subset of `NSPasteboard` supported by TuckClip.
///
/// AppKit objects stay on the main actor. Returned captures contain only value types,
/// so they can safely be handed to persistence code.
@MainActor
final class PasteboardReader {
    static let internalMarkerType = NSPasteboard.PasteboardType(
        "io.github.iajihga.tuckclip.internal-item"
    )

    private static let ignoredTypeNames: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.transienttype",
        "org.nspasteboard.autogeneratedtype"
    ]

    private let pasteboard: NSPasteboard
    private let settings: AppSettings

    init(
        pasteboard: NSPasteboard = .general,
        settings: AppSettings? = nil
    ) {
        self.pasteboard = pasteboard
        self.settings = settings ?? .shared
    }

    var changeCount: Int {
        pasteboard.changeCount
    }

    var accessStatus: PasteboardAccessStatus {
        guard #available(macOS 15.4, *) else {
            return .unavailable
        }

        switch pasteboard.accessBehavior {
        case .default:
            return .notDetermined
        case .ask:
            return .ask
        case .alwaysAllow:
            return .alwaysAllow
        case .alwaysDeny:
            return .alwaysDeny
        @unknown default:
            return .notDetermined
        }
    }

    /// Reads using the application that is frontmost at call time.
    ///
    /// Callers that observed an application activation boundary should use the
    /// source-aware overload so a copy made immediately before Command-Tab is not
    /// incorrectly attributed to the newly active app.
    func readCapture(timestamp: Date = .now) -> ClipboardCapture? {
        readCapture(
            timestamp: timestamp,
            sourceApplication: NSWorkspace.shared.frontmostApplication
        )
    }

    /// Returns the current portable clipboard value, or `nil` when it is private,
    /// generated by TuckClip, excluded by source application, unsupported, or too large.
    /// Passing `nil` records no source metadata and is useful for deterministic tests.
    func readCapture(
        timestamp: Date = .now,
        sourceApplication: NSRunningApplication?
    ) -> ClipboardCapture? {
        guard accessStatus.allowsBackgroundCapture else {
            return nil
        }

        // Resolve and filter the supplied source app before reading payload bytes.
        // This avoids even triggering clipboard access for a known password manager.
        let sourceBundleIdentifier = sourceApplication?.bundleIdentifier
        guard !isExcludedSource(bundleIdentifier: sourceBundleIdentifier) else {
            return nil
        }

        guard let items = pasteboard.pasteboardItems,
              !items.isEmpty,
              !containsInternalMarker(items),
              !containsSensitiveOrTransientType(items) else {
            return nil
        }

        let sourceAppName = sourceApplication?.localizedName

        if let filePaths = readFilePaths(from: items) {
            return ClipboardCapture(
                kind: .files,
                filePaths: filePaths,
                sourceAppName: sourceAppName,
                sourceBundleIdentifier: sourceBundleIdentifier,
                timestamp: timestamp,
                fingerprint: fingerprint(kind: .files, filePaths: filePaths)
            )
        }

        if settings.capturesImages, let imageData = readPNG(from: items) {
            return ClipboardCapture(
                kind: .image,
                imageData: imageData,
                sourceAppName: sourceAppName,
                sourceBundleIdentifier: sourceBundleIdentifier,
                timestamp: timestamp,
                fingerprint: fingerprint(kind: .image, payload: imageData)
            )
        }

        guard let textValue = readText(from: items) else {
            return nil
        }
        guard !containsHighConfidencePrivateKey(in: textValue) else {
            return nil
        }

        let kind: ClipKind = isWebLink(textValue) ? .link : .text
        return ClipboardCapture(
            kind: kind,
            plainText: textValue,
            sourceAppName: sourceAppName,
            sourceBundleIdentifier: sourceBundleIdentifier,
            timestamp: timestamp,
            fingerprint: fingerprint(kind: kind, payload: Data(textValue.utf8))
        )
    }

    private func containsInternalMarker(_ items: [NSPasteboardItem]) -> Bool {
        items.contains { $0.types.contains(Self.internalMarkerType) }
    }

    private func containsSensitiveOrTransientType(_ items: [NSPasteboardItem]) -> Bool {
        items.contains { item in
            item.types.contains { type in
                Self.ignoredTypeNames.contains(type.rawValue.lowercased())
            }
        }
    }

    private func isExcludedSource(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        let normalizedIdentifier = bundleIdentifier.lowercased()

        if normalizedIdentifier == Bundle.main.bundleIdentifier?.lowercased() {
            return true
        }

        return settings.excludedBundleIdentifiers.contains {
            $0.caseInsensitiveCompare(normalizedIdentifier) == .orderedSame
        }
    }

    private func readFilePaths(from items: [NSPasteboardItem]) -> [String]? {
        var paths: [String] = []

        for item in items {
            guard let value = item.string(forType: .fileURL),
                  let url = URL(string: value),
                  url.isFileURL else {
                continue
            }
            paths.append(url.standardizedFileURL.path)
        }

        guard !paths.isEmpty else { return nil }

        let byteCount = paths.reduce(into: 0) { total, path in
            total += path.lengthOfBytes(using: .utf8) + 1
        }
        guard byteCount <= AppSettings.maximumCaptureSizeBytes else { return nil }
        return paths
    }

    private func readPNG(from items: [NSPasteboardItem]) -> Data? {
        for item in items {
            if let pngData = item.data(forType: .png) {
                guard pngData.count <= AppSettings.maximumCaptureSizeBytes else {
                    return nil
                }
                return pngData
            }

            guard let tiffData = item.data(forType: .tiff) else { continue }
            guard tiffData.count <= AppSettings.maximumCaptureSizeBytes,
                  let image = NSImage(data: tiffData),
                  let canonicalTIFF = image.tiffRepresentation,
                  let bitmap = NSBitmapImageRep(data: canonicalTIFF),
                  let pngData = bitmap.representation(using: .png, properties: [:]),
                  pngData.count <= AppSettings.maximumCaptureSizeBytes else {
                return nil
            }
            return pngData
        }
        return nil
    }

    private func readText(from items: [NSPasteboardItem]) -> String? {
        var values: [String] = []
        var byteCount = 0

        for item in items {
            let value = item.string(forType: .string)
                ?? item.string(forType: .URL)
            guard let value, !value.isEmpty else { continue }

            byteCount += value.lengthOfBytes(using: .utf8)
            if !values.isEmpty { byteCount += 1 }
            guard byteCount <= AppSettings.maximumTextCaptureSizeBytes else {
                return nil
            }
            values.append(value)
        }

        guard !values.isEmpty else { return nil }
        return values.joined(separator: "\n")
    }

    private func isWebLink(_ value: String) -> Bool {
        let candidate = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !candidate.contains(where: \.isWhitespace),
              let url = URL(string: candidate),
              let scheme = url.scheme?.lowercased() else {
            return false
        }
        return ["http", "https", "ftp", "mailto"].contains(scheme)
    }

    /// Matches only standard, standalone ASCII-armored private-key boundaries.
    /// It deliberately does not guess at passwords, tokens or arbitrary base64.
    private func containsHighConfidencePrivateKey(in text: String) -> Bool {
        text.components(separatedBy: .newlines).contains { line in
            let boundary = line
                .trimmingCharacters(in: .whitespacesAndNewlines)
                .uppercased()

            guard boundary.hasPrefix("-----BEGIN ") else {
                return false
            }
            return boundary.hasSuffix(" PRIVATE KEY-----")
                || boundary == "-----BEGIN PGP PRIVATE KEY BLOCK-----"
                || boundary == "-----BEGIN PGP SECRET KEY BLOCK-----"
        }
    }

    private func fingerprint(kind: ClipKind, filePaths: [String]) -> String {
        fingerprint(
            kind: kind,
            payload: Data(filePaths.joined(separator: "\u{0}").utf8)
        )
    }

    private func fingerprint(kind: ClipKind, payload: Data) -> String {
        var material = Data(kind.rawValue.utf8)
        material.append(0)
        material.append(payload)
        return SHA256.hash(data: material).map {
            String(format: "%02x", $0)
        }.joined()
    }
}
